// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import MobileMenuController from "./mobile_menu_controller"
application.register("mobile-menu", MobileMenuController)

import QuantityController from "./quantity_controller"
application.register("quantity", QuantityController)

import ImageGalleryController from "./image_gallery_controller"
application.register("image-gallery", ImageGalleryController)

import SlideshowController from "./slideshow_controller"
application.register("slideshow", SlideshowController)

import TickerController from "./ticker_controller"
application.register("ticker", TickerController)

import StripePaymentController from "./stripe_payment_controller"
application.register("stripe-payment", StripePaymentController)

import ToastController from "./toast_controller"
application.register("toast", ToastController)
