production:
  expire_abandoned_carts:
    class: ExpireAbandonedCartsJob
    schedule: every hour

  check_low_stock:
    class: CheckLowStockJob
    schedule: at 8am every day

  clear_solid_queue_finished_jobs:
    command: "SolidQueue::Job.clear_finished_in_batches(sleep_between_batches: 0.3)"
    schedule: every hour at minute 12
